import { Download, Printer } from "lucide-react";

interface Props {
  open: boolean;
  onClose: () => void;
}

export default function AIReportModal({ open, onClose }: Props) {
  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="w-[750px] rounded-3xl bg-white p-8 shadow-2xl">
        <h2 className="mb-2 text-3xl font-bold">
          🤖 AI Fleet Executive Report
        </h2>
        <div className="flex gap-3">
          <button className="rounded-xl border px-4 py-2 hover:bg-slate-100">
            <Printer size={18} />
          </button>

          <button className="rounded-xl border px-4 py-2 hover:bg-slate-100">
            <Download size={18} />
          </button>
        </div>

        <p className="mb-8 text-slate-500">
          Generated by TransitOps Intelligence Engine
        </p>

        <div className="space-y-6">
          <div>
            <h3 className="font-semibold text-indigo-600">Fleet Health</h3>

            <p>
              Fleet health remains excellent with an overall score of 94%. Two
              vehicles should undergo preventive maintenance within the next
              five days to avoid downtime.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-indigo-600">
              Driver Performance
            </h3>

            <p>
              Driver safety averages 91%. Rahul has achieved the highest safety
              score this week with zero incidents.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-indigo-600">
              Operational Efficiency
            </h3>

            <p>
              Fleet utilization can improve by approximately 14% through better
              allocation of idle vehicles.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-indigo-600">AI Recommendation</h3>

            <ul className="list-disc pl-5 space-y-2">
              <li>Schedule preventive maintenance for TX-123-AB.</li>
              <li>Assign idle vehicles to pending deliveries.</li>
              <li>Continue monitoring driver fatigue patterns.</li>
            </ul>
          </div>
        </div>

        <button
          onClick={onClose}
          className="mt-8 rounded-xl bg-indigo-600 px-6 py-3 text-white"
        >
          Close
        </button>
      </div>
    </div>
  );
}
