import { useCallback, useEffect, useMemo, useState } from "react";
import AppShell from "@/components/layout/AppShell";
import { adminService, type AdminOverview, type AdminRole, type AdminUser, type AuditLog } from "@/services/adminService";
import { Activity, CheckCircle2, KeyRound, Shield, UserPlus, Users, XCircle } from "lucide-react";

const roles: AdminRole[] = ["admin", "fleet-manager", "dispatcher", "safety-officer", "financial-analyst"];
const roleLabel = (role: string) => role.replaceAll("-", " ").replace(/\b\w/g, (c) => c.toUpperCase());

export default function AdminPage() {
  const [overview, setOverview] = useState<AdminOverview | null>(null);
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [logs, setLogs] = useState<AuditLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", password: "", role: "fleet-manager" as AdminRole });

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [nextOverview, nextUsers, nextLogs] = await Promise.all([adminService.overview(), adminService.users(), adminService.auditLogs()]);
      setOverview(nextOverview); setUsers(nextUsers); setLogs(nextLogs);
    } catch (err) { setError(err instanceof Error ? err.message : "Unable to load admin data."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const activeUsers = useMemo(() => users.filter((u) => u.is_active).length, [users]);
  async function toggleUser(user: AdminUser) { try { await adminService.updateUser(user.id, { is_active: !user.is_active }); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update user."); } }
  async function changeRole(user: AdminUser, role: AdminRole) { try { await adminService.updateUser(user.id, { role }); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update role."); } }
  async function createUser(e: React.FormEvent) { e.preventDefault(); try { await adminService.createUser(form); setForm({ name:"", email:"", password:"", role:"fleet-manager" }); setShowCreate(false); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create user."); } }

  return <AppShell><div className="space-y-7 pb-10">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-indigo-600">Security & governance</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Admin Control Center</h1><p className="mt-2 text-sm text-slate-500">Manage users, roles, access and the system audit trail from one place.</p></div><button onClick={() => setShowCreate(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-100 hover:bg-indigo-700"><UserPlus size={17}/> Add user</button></div>
    {error && <div className="rounded-xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-5">{[["Total users",overview?.total_users ?? 0,Users],["Active users",overview?.active_users ?? activeUsers,CheckCircle2],["Fleet size",overview?.fleet_size ?? 0,Shield],["Active trips",overview?.active_trips ?? 0,Activity],["System health",overview?.system_health ?? "Checking…",CheckCircle2]].map(([label,value,Icon]) => <div key={String(label)} className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{String(label)}</p><div className="rounded-xl bg-indigo-50 p-2.5 text-indigo-600"><Icon size={18}/></div></div><p className="mt-4 text-2xl font-bold capitalize text-slate-900">{loading ? "—" : String(value)}</p></div>)}</div>
    <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-bold text-slate-900">User management</h2><p className="mt-1 text-sm text-slate-500">Enable, disable and change roles without touching the database.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{users.length} accounts</span></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-3">User</th><th className="px-6 py-3">Role</th><th className="px-6 py-3">Status</th><th className="px-6 py-3">Created</th><th className="px-6 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map((u) => <tr key={u.id} className="hover:bg-slate-50/70"><td className="px-6 py-4"><p className="font-semibold text-slate-900">{u.name}</p><p className="text-xs text-slate-500">{u.email}</p></td><td className="px-6 py-4"><select value={u.role} onChange={(e) => void changeRole(u, e.target.value as AdminRole)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold capitalize outline-none">{roles.map((r) => <option key={r} value={r}>{roleLabel(r)}</option>)}</select></td><td className="px-6 py-4"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${u.is_active ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{u.is_active ? <CheckCircle2 size={13}/> : <XCircle size={13}/>} {u.is_active ? "Active" : "Disabled"}</span></td><td className="px-6 py-4 text-xs text-slate-500">{u.created_at ? new Date(u.created_at).toLocaleDateString() : "—"}</td><td className="px-6 py-4 text-right"><button onClick={() => void toggleUser(u)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">{u.is_active ? "Disable" : "Enable"}</button></td></tr>)}</tbody></table></div></section>
    <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-bold text-slate-900">Audit log</h2><p className="mt-1 text-sm text-slate-500">Recent authentication and administrative actions.</p></div><div className="divide-y divide-slate-100">{logs.length ? logs.slice(0, 30).map((log) => <div key={log.id} className="flex flex-col gap-2 px-6 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-slate-800">{log.action.replaceAll("_", " ")}</p><p className="text-xs text-slate-500">{log.user_email}{log.target ? ` · ${log.target}` : ""}{log.details ? ` · ${log.details}` : ""}</p></div><time className="text-xs text-slate-400">{new Date(log.created_at).toLocaleString()}</time></div>) : <div className="px-6 py-10 text-center text-sm text-slate-500">No audit events yet.</div>}</div></section>
  </div>
  {showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm"><form onSubmit={createUser} className="w-full max-w-lg rounded-[28px] bg-white p-7 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold text-slate-900">Create account</h2><p className="mt-1 text-sm text-slate-500">Provision a new TransPilot user.</p></div><button type="button" onClick={() => setShowCreate(false)} className="text-slate-400">✕</button></div><div className="mt-6 space-y-4"><input required placeholder="Full name" value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} className="h-11 w-full rounded-xl border border-slate-200 px-4 outline-none focus:border-indigo-500"/><input required type="email" placeholder="Email address" value={form.email} onChange={(e) => setForm({...form,email:e.target.value})} className="h-11 w-full rounded-xl border border-slate-200 px-4 outline-none focus:border-indigo-500"/><input required minLength={8} type="password" placeholder="Temporary password" value={form.password} onChange={(e) => setForm({...form,password:e.target.value})} className="h-11 w-full rounded-xl border border-slate-200 px-4 outline-none focus:border-indigo-500"/><select value={form.role} onChange={(e) => setForm({...form,role:e.target.value as AdminRole})} className="h-11 w-full rounded-xl border border-slate-200 px-4 capitalize outline-none">{roles.map((r) => <option key={r} value={r}>{roleLabel(r)}</option>)}</select></div><button type="submit" className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 py-3 text-sm font-semibold text-white hover:bg-indigo-700"><KeyRound size={16}/> Create account</button></form></div>}
  </AppShell>;
}
